# Testes de ponta a ponta dos programas `grafos` e `estudos` (executado por ctest).
# Variaveis: GRAFOS, ESTUDOS, DADOS (tests/dados), TMP (pasta de trabalho).

file(REMOVE_RECURSE "${TMP}")
file(MAKE_DIRECTORY "${TMP}")

function(rodar esperado_codigo)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE codigo OUTPUT_VARIABLE saida ERROR_VARIABLE erro)
    if(NOT "${codigo}" STREQUAL "${esperado_codigo}")
        message(FATAL_ERROR "codigo ${codigo} (esperado ${esperado_codigo}) em: ${ARGN}\nsaida:\n${saida}\nerro:\n${erro}")
    endif()
    set(SAIDA "${saida}" PARENT_SCOPE)
    set(ERRO "${erro}" PARENT_SCOPE)
endfunction()

function(exigir_texto texto trecho)
    string(FIND "${texto}" "${trecho}" pos)
    if(pos EQUAL -1)
        message(FATAL_ERROR "trecho nao encontrado: '${trecho}'\nem:\n${texto}")
    endif()
endfunction()

function(comparar arquivo esperado)
    file(READ "${arquivo}" conteudo)
    if(NOT conteudo STREQUAL esperado)
        message(FATAL_ERROR "conteudo de ${arquivo} difere.\nobtido:\n${conteudo}\nesperado:\n${esperado}")
    endif()
endfunction()

set(FIG "${DADOS}/figura1.txt")
set(EST_ESPERADO "# Estatisticas do grafo\nvertices: 5\narestas: 5\ngrau_minimo: 1\ngrau_maximo: 4\ngrau_medio: 2.0000\nmediana_grau: 2.0\n\n# Componentes conexas\nnum_componentes: 1\n\ncomponente 1 (tamanho 5):\n1 2 3 4 5\n")
set(BFS_ESPERADO "# BFS raiz=1\n# vertice pai nivel ordem\n1 0 0 1\n2 1 1 2\n3 5 2 4\n4 5 2 5\n5 1 1 3\n")
set(DFS_ESPERADO "# DFS raiz=1\n# vertice pai nivel ordem\n1 0 0 1\n2 1 1 2\n3 5 3 4\n4 5 3 5\n5 2 2 3\n")

foreach(repr lista matriz)
    rodar(0 "${GRAFOS}" estatisticas "${FIG}" --repr ${repr} -o "${TMP}/est_${repr}.txt")
    exigir_texto("${SAIDA}" "n = 5, m = 5")
    comparar("${TMP}/est_${repr}.txt" "${EST_ESPERADO}")
    rodar(0 "${GRAFOS}" bfs "${FIG}" --origem 1 --repr ${repr} -o "${TMP}/bfs_${repr}.txt")
    comparar("${TMP}/bfs_${repr}.txt" "${BFS_ESPERADO}")
    rodar(0 "${GRAFOS}" dfs "${FIG}" --repr ${repr} --origem 1 -o "${TMP}/dfs_${repr}.txt")
    comparar("${TMP}/dfs_${repr}.txt" "${DFS_ESPERADO}")
    rodar(0 "${GRAFOS}" distancia "${FIG}" 3 4 --repr ${repr} --caminho)
    exigir_texto("${SAIDA}" "distancia(3, 4) = 2")
    exigir_texto("${SAIDA}" "caminho: 3 5 4")
    foreach(alg --ingenuo --aproximado --exato)
        rodar(0 "${GRAFOS}" diametro "${FIG}" --repr ${repr} ${alg})
        exigir_texto("${SAIDA}" "diametro: 2\n")
        exigir_texto("${SAIDA}" "exato: sim")
    endforeach()
endforeach()

rodar(0 "${GRAFOS}" estatisticas "${DADOS}/repetidas_lacos.txt" -o "${TMP}/rep.txt")
exigir_texto("${SAIDA}" "linhas de aresta = 4, lacos ignorados = 1, repetidas ignoradas = 2")

file(WRITE "${TMP}/desconexo.txt" "8\n1 2\n2 3\n5 6\n")
rodar(0 "${GRAFOS}" distancia "${TMP}/desconexo.txt" 1 5)
exigir_texto("${SAIDA}" "distancia(1, 5) = infinito")
rodar(0 "${GRAFOS}" diametro "${TMP}/desconexo.txt" --limite 0)
exigir_texto("${SAIDA}" "tempo_esgotado: sim")

rodar(0 "${GRAFOS}" --help)
exigir_texto("${SAIDA}" "grafos diametro")
rodar(2 "${GRAFOS}")
rodar(2 "${GRAFOS}" comando_inexistente "${FIG}")
rodar(2 "${GRAFOS}" estatisticas "${FIG}")
rodar(2 "${GRAFOS}" bfs "${FIG}" -o "${TMP}/x.txt")
rodar(2 "${GRAFOS}" bfs "${FIG}" --origem abc -o "${TMP}/x.txt")
rodar(2 "${GRAFOS}" estatisticas "${FIG}" --repr arvore -o "${TMP}/x.txt")
rodar(2 "${GRAFOS}" diametro "${FIG}" --ingenuo --exato)
rodar(1 "${GRAFOS}" bfs "${FIG}" --origem 9 -o "${TMP}/x.txt")
exigir_texto("${ERRO}" "vertice 9 fora do intervalo 1..5")
rodar(1 "${GRAFOS}" estatisticas "${TMP}/nao_existe.txt" -o "${TMP}/x.txt")
file(WRITE "${TMP}/ruim.txt" "5\n1 2\n1 7\n")
rodar(1 "${GRAFOS}" estatisticas "${TMP}/ruim.txt" -o "${TMP}/x.txt")
exigir_texto("${ERRO}" "linha 3: vertice 7 fora do intervalo 1..5")
file(WRITE "${TMP}/enorme.txt" "2000000000\n1 2\n")
rodar(1 "${GRAFOS}" estatisticas "${TMP}/enorme.txt" --repr matriz -o "${TMP}/x.txt")
exigir_texto("${ERRO}" "matriz exigiria")

# Lista com n absurdo: recusada so pelo n, antes de alocar. Roda sob ulimit -v para que, se a
# checagem falhar, o erro seja bad_alloc e nao um OOM do WSL. Pulado com sanitizers (ASan
# reserva memoria virtual demais para funcionar com ulimit -v).
if(NOT SANITIZERS)
    set(LIMITADO sh -c "ulimit -v 4000000 && exec \"$0\" \"$@\"")
    rodar(1 ${LIMITADO} "${GRAFOS}" estatisticas "${TMP}/enorme.txt" -o "${TMP}/x.txt")
    exigir_texto("${ERRO}" "lista exigiria pelo menos")
    rodar(1 ${LIMITADO} "${ESTUDOS}" --grafo "${TMP}/enorme.txt" --repr lista --saida "${TMP}/res")
    exigir_texto("${ERRO}" "lista exigiria pelo menos")
endif()

# estudos: lista e matriz no grafo desconexo (n < 30: vertices 10, 20, 30 inexistentes)
foreach(repr lista matriz)
    rodar(0 "${ESTUDOS}" --grafo "${TMP}/desconexo.txt" --repr ${repr} --saida "${TMP}/res" --semente 7)
    file(READ "${TMP}/res/desconexo_${repr}.csv" csv)
    exigir_texto("${csv}" "chave,valor\n")
    exigir_texto("${csv}" "representacao,${repr}\n")
    exigir_texto("${csv}" "memoria_status,ok\n")
    exigir_texto("${csv}" "num_buscas,8\n")
    exigir_texto("${csv}" "pai_dfs_raiz3_v10,inexistente\n")
    exigir_texto("${csv}" "dist_10_20,inexistente\n")
    exigir_texto("${csv}" "num_componentes,5\n")
    exigir_texto("${csv}" "maior_componente,3\n")
    exigir_texto("${csv}" "menor_componente,1\n")
    if(NOT EXISTS "${TMP}/res/desconexo_${repr}_estatisticas.txt" OR EXISTS "${TMP}/res/desconexo_${repr}.csv.tmp")
        message(FATAL_ERROR "arquivos de saida do estudos inesperados (${repr})")
    endif()
endforeach()
file(READ "${TMP}/res/desconexo_lista.csv" csv)
exigir_texto("${csv}" "diam_exato_valor,2\n")
exigir_texto("${csv}" "diam_aprox_exato,sim\n")
file(READ "${TMP}/res/desconexo_matriz.csv" csv)
exigir_texto("${csv}" "diametro_status,nao_calculado_na_matriz\n")

# grafo com 40 vertices: pais e distancias existem
set(caminho40 "40\n")
foreach(i RANGE 1 39)
    math(EXPR j "${i} + 1")
    string(APPEND caminho40 "${i} ${j}\n")
endforeach()
file(WRITE "${TMP}/caminho40.txt" "${caminho40}")
rodar(0 "${ESTUDOS}" --grafo "${TMP}/caminho40.txt" --repr lista --saida "${TMP}/res")
file(READ "${TMP}/res/caminho40_lista.csv" csv)
exigir_texto("${csv}" "pai_bfs_raiz1_v10,9\n")
exigir_texto("${csv}" "pai_dfs_raiz3_v20,19\n")
exigir_texto("${csv}" "pai_bfs_raiz2_v10,9\n")
exigir_texto("${csv}" "dist_10_30,20\n")
exigir_texto("${csv}" "num_buscas,40\n")
exigir_texto("${csv}" "diam_exato_valor,39\n")

rodar(0 "${ESTUDOS}" --grafo "${TMP}/enorme.txt" --repr matriz --saida "${TMP}/res")
file(READ "${TMP}/res/enorme_matriz.csv" csv)
exigir_texto("${csv}" "memoria_status,inviavel\n")
if(EXISTS "${TMP}/res/enorme_lista.csv")
    message(FATAL_ERROR "lista inviavel nao pode gerar CSV")
endif()
rodar(2 "${ESTUDOS}" --grafo "${FIG}" --repr arvore --saida "${TMP}/res")
rodar(1 "${ESTUDOS}" --grafo "${TMP}/ruim.txt" --repr lista --saida "${TMP}/res")
if(EXISTS "${TMP}/res/ruim_lista.csv")
    message(FATAL_ERROR "estudos com erro nao pode deixar CSV final")
endif()

# gerar_grafo: formato valido, sem lacos, reprodutivel pela semente
rodar(0 "${GERAR}" --n 50 --m 200 --semente 5 -o "${TMP}/sint1.txt")
rodar(0 "${GERAR}" --n 50 --m 200 --semente 5 -o "${TMP}/sint2.txt")
file(READ "${TMP}/sint1.txt" s1)
file(READ "${TMP}/sint2.txt" s2)
if(NOT s1 STREQUAL s2)
    message(FATAL_ERROR "gerar_grafo nao e reprodutivel")
endif()
rodar(0 "${GRAFOS}" estatisticas "${TMP}/sint1.txt" -o "${TMP}/sint_est.txt")
exigir_texto("${SAIDA}" "linhas de aresta = 200, lacos ignorados = 0")
rodar(2 "${GERAR}" --n 1 --m 3 -o "${TMP}/x.txt")
rodar(2 "${GERAR}" --n 10 -o "${TMP}/x.txt")

file(REMOVE_RECURSE "${TMP}")
message(STATUS "programas: ok")
